Citizen.CreateThread(function()
    local blip = AddBlipForCoord(Config.Location.Ped.Buying.position)
    SetBlipScale(blip, Config.Generic.Blips.size)
    SetBlipSprite(blip, Config.Generic.Blips.id)
    SetBlipColour(blip, Config.Generic.Blips.color)
    SetBlipAsShortRange(blip, true)
    AddTextEntry("BLIPS_LOC", Config.Generic.Blips.name)
    BeginTextCommandSetBlipName("BLIPS_LOC")
    EndTextCommandSetBlipName(blip)
end)